# Generated by Django 2.2.12 on 2023-05-02 18:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0007_auto_20230502_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='payround2',
            field=otree.db.models.IntegerField(default=2, null=True),
        ),
    ]
